/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import agentes.AgentePolicia;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import util.AcumuladoJugador;
import util.ResultadoJugador;

/**
 *
 * @author pedroj
 */
public class ClasificacionJFrame extends javax.swing.JFrame {
    private final AgentePolicia myAgent;
    private final HashMap<String, AcumuladoJugador> clasificacion;

    /**
     * Creates new form ClasificacionJFrame
     */
    public ClasificacionJFrame(AgentePolicia myAgent) {
        initComponents();
        this.myAgent = myAgent;
        this.setTitle("Clasificación: " + myAgent.getName());
        clasificacion = new HashMap();
    }
    
    public void presentarClasificacion(List<ResultadoJugador> clasificacionJugadores) {
        
        this.setVisible(true);
        this.listaJugadores.setText(null);
        this.listaCondenas.setText(null);
        
        // Actualizamos la clasificacion
        for (ResultadoJugador resultadoJugador : clasificacionJugadores) {
            String nombreJugador = resultadoJugador.getJugador().getNombre();
            AcumuladoJugador resultado = clasificacion.get(nombreJugador); 
            if ( resultado != null) {
                int condena = resultado.getTotalCondena();
                resultado.setTotalCondena(condena + resultadoJugador.getTiempoCondena() );
                int partidas = resultado.getPartidasJugadas();
                resultado.setPartidasJugadas(partidas + 1);
                clasificacion.put(nombreJugador, resultado);
            } else {
                resultado = new AcumuladoJugador( resultadoJugador.getJugador() ,
                            resultadoJugador.getTiempoCondena(), 1);
                clasificacion.put(nombreJugador, resultado);
            }
        }
        // Presentamos la clasificacion
        List<AcumuladoJugador> presentarClasificacion;
        presentarClasificacion = new ArrayList(clasificacion.values());
        
        Collections.sort(presentarClasificacion);
        for (AcumuladoJugador resultadoJugador : presentarClasificacion) {
            listaJugadores.append(resultadoJugador.getJugador().getNombre() + 
                    " (" + resultadoJugador.getPartidasJugadas() + ")\n");
            listaCondenas.append(Integer.toString(resultadoJugador.getTotalCondena()) + "\n");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaJugadores = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaCondenas = new javax.swing.JTextArea();

        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        listaJugadores.setEditable(false);
        listaJugadores.setRows(5);
        jScrollPane2.setViewportView(listaJugadores);

        listaCondenas.setEditable(false);
        listaCondenas.setRows(5);
        jScrollPane3.setViewportView(listaCondenas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea listaCondenas;
    private javax.swing.JTextArea listaJugadores;
    // End of variables declaration//GEN-END:variables
}
